[package]
name = "barnes"
version = "0.1.0"
authors = ["Martin Magakian <dev.martin.magakian@gmail.com>"]
description = "A multithreaded Barnes Hut Algorithm implementation."

[lib]

name = "barnes"
path = "src/lib.rs"